## NUMPY

In [1]:
import numpy as np
import pandas as pd

## Applications of numpy


In [ ]:
1. Linear Algebra
2. Statistics
3. Trigonometry
4. Matrix Operations
5. IMage Processing
6. Logarithmic 

## Properties


In [ ]:
1. It is a collection homogeneous datatypes
2. Numpy is faster than List
3. Numpy is written in C and C++ Language (Partially in Python)
4. C Language is Faster than Python

## Functions

In [ ]:
1. np.array()
# syntax -->np.array(object,dtype,ndim=0,1,2,3)

2. array.ndim()
# syntax --> array1.ndim() --> returns dimension of array

3. array.shape()
# syntax --> array1.shape() --> returns tuple(number of rows , number of columns)
# to get no of rows --> array1.shape()[0]
# to get no of columns --> array1.shape()[-1]

4.array.reshape()
# it is used to change shape of arrray
# here no of elements in array should be always same after reshaping else we get get
# eg 1d of 12 elements can be reshaped to other shapes only containing 12 elements
# syntax --> array1.reshape(2,3)

5. array.tolist()
# Dimensioanl Numpy array tolist
# convert any dim array to list

6. np.nditer()
# it is used to get all elements from array without using nested if statements
# syntax --> np.nditer(array1)

7. np.ndenumerate()
# ndenemerate is used to get index and value of items in array
# syntax --> np.ndenumerate(array1)

8. array.flatten() # copy
# it is used to flatten any dim array to 1d array
# syntax --> array1.flatten()

9. array.ravel()  # reference
# it just create ref to array
# any changes made in original array reflects in ref obj
# syntax --> array1.ravel()

10. array.copy()
# it is ussed to create copy of array
# here deep copy is created hence changes made in original array is not reflected in copy array
# syntax --> array1.copy()

11. np.zeros()
# it is used to create array containing only zeros
# syntax --> np.zeros((shape),dtype)

12. np.ones()
# it is used to create array containing only ones
# syntax --> np.ones((shape),dtype)

13. np.full()
# it is used to create array containing only any number passed 
# syntax --> np.full((shape),value to fill array,dtype)

14. np.arange()
# syntax --> np.arange(start value , end value , dtype)

15. np.around()
# used to round values to given digit in array of any shape
# syntax --> np.around(array1)

16. np.linspace()
# returns evenly spaces values between start and end values
# syntax --> np.linspace(start , end , number of elements required)

17. np.eye()
# creates 2d array which contains 1 as digonal element and other elements zero
# syntax --> np.eye(no of rows, no of column(optional) , dtype)

18. np.identity()
# creates identity matrix 
# syntax --> np.identity(no of rows,dtype)

19. np.random:

    1. np.random.rand()
#     creates array of given shape containing random values between 0-1
#     syntax --> np.random.rand(no of rows , no of columns)
    
    2. np.random.randint()
#     creates array of given shape containing random values between any two values
#     syntax --> np.random.randint(val1,val2,(no of rows , no of columns))
    
    3. np.random.randn()
    
    4. np.random.ranf()
#     creates array of given shape containing random values between 0-1
#     syntax --> np.random.ranf((no of rows , no of columns))

20. np.append()
# append value to end of array
# default axis is none we can specify axis as 0 or 1
# syntax --> np.append(array1,array2)

21. np.concatenate()
# used to concatnate arrays
# default axix is 0 if we make axis as none it will flatten arrays
# syntax --> np.concatenate(arra1,array2,..)

22. np.sort()
# syntax --> np.sort(array1) ascending order
#           -np.sort(array1) descending order

23. np.add()
# array are required to have same shape 
# syntax --> np.add(array1,array2)

24. np.multiply()
# array are required to have same shape
# syntax --> np.multiply(array1,array2)

25. np.dot()
# gives dot product of matrix
# here no of column of first matrix should be eqaul to no of rows of second matrix

26. np.floor()
# performs floor division on each item in array
# syntax --> np.floor(array1)

27. np.ceil() # next value if .something is present 10.0000009 --> 10.
# syntax --> np.ceil(array1)
# converts values to nxt int like 4.99-->5.00 4.00009-->5.00 and 4.0000-->4.00

28. np.sqrt()
# used to find sruare root of all elements in array
#  syntax --> np.sqrt(array1)

29. np.cbrt()
# used to find cube root of items in array
# syntax --> np.cbrt(array1)

30. np.where()
# used to find index of perticular item in array
# returns list of indexs

# numpy statistics functions

1. np.mean()
# used to find mean value from array
# syntax --> np.mean(array1)

2. np.median()
# used to find median value from array
# syntax --> np.median(array1)

3. np.std()
# used to find value of standard deviation
# syntax --> np.std(array1)

4. np.var()
# used to find varaiance 
# syntax --> np.var(array1)

5. np.sum()
# used to find sum of values from array
# syntax --> np.sum(array1)

6. np.max()
# used to find max value from array
# syntax --> np.max(array1)

7. np.min()
# used to find min value from array
# syntax --> np.min(array1)

8. scipy.stats.mode()
# used to find moad value from array
# mode is not present in numpy lib so we need to import mode from scipy lib
# from scipy.stats import mode
# syntax --> mode(array1)

# numpy linear algebra functions

1. np.linalg.solve()
# it is used to solve quadratic equations
# syntax --> np.linalg.solve(array1,array2)

2. np.linalg.inv()
# it is used to get inverse of array
# syntax --> np.linalg.inv()

3. np.polynomial.Polynomial()
# it is used to create polynomial equation
# syntax --> np.polynomial.Polynomial

4.poly.roots()
# it is used to find roots of given polynomial function
# syntax --> equation1.roots()

5. np.linalg.eig()
# it is used to get eigen vectors of matrix
# syntax --> np.linalg.eig(array1)

6. np.linalg.eigvals()
# it is used to get eigen values
# syntax --> np.linalg.eigenvalues(array1)

# numpy lograthmic functions

1. np.log()
# it gives values of natura log
# syntax --> np.log(array1)

2. np.log2()
# it gives values of log to base 2
# syntax --> np.log2(array1)

3. np.log10()
# it gives values of log to base 10
# syntax --> np.log10(array1)

# numpy trigonometry functions

1. np.sin()
# used to get sin values

2. np.cos()
# used to get cos values

3. np.tan()
# used to get tan values

4. np.deg2rad()
# used to convert degree to radians

5. np.rad2deg()
# used to conver radians to degree

### np.array

In [4]:
# np.array() is used to create numpy array

a1 = np.array([1,2,3,4,5])
print(a1)

l1=[1,2,3,4]
a2= np.array(l1)
print(a2)

s1 = {3,4,5,6,7,8}
a3 = np.array(list(s1))
print(a3)

n1=[2,3,4,4.4,5,6]
a4=np.array(n1)
print(a4) # here all values will be converted to float

n1=[2,3,4,4.4,5+7j,6]
a5=np.array(n1)
print(a5) # here all values will be converted to complex

[1 2 3 4 5]
[1 2 3 4]
[3 4 5 6 7 8]
[2.  3.  4.  4.4 5.  6. ]
[2. +0.j 3. +0.j 4. +0.j 4.4+0.j 5. +7.j 6. +0.j]


### type casting in np array

In [ ]:
int>>string
int>>float
int>>complex
float>>int
float>>str
complex>>to  -->we cannot typecast complex datatype

In [9]:
# methodes for crateing np array with int

a1=np.array([1,2,3,4],dtype=int)
print(a1)
a2=np.array([1,2,3,4],dtype='int')
print(a2)
a3=np.array([1,2,3,4],dtype='i')
print(a3)


# type casting int to float
a1=np.array([1,2,3,4],dtype=float)
print(a1)
a2=np.array([1,2,3,4],dtype='f')
print(a2)
a3=np.array([1,2,3,4],dtype='float')
print(a3)

# typecasting int to complex
a1=np.array([1,2,3,4],dtype=complex)
print(a1)
a2=np.array([1,2,3,4],dtype='complex')
print(a2)

# typecasting int to str
a1=np.array([1,2,3,4],dtype=str)
print(a1)
a2=np.array([1,2,3,4],dtype='str')
print(a2)

# type casting from float to int

a1=np.array([1.1,2.2,3.3,4.4],dtype=int)
print(a1)
a2=np.array([1.1,2.2,3.3,4.4],dtype='int')
print(a2)
a1=np.array([1.1,2.2,3.3,4.4],dtype='i')
print(a1)

# typecasting from float to str

a1=np.array([1.1,2.2,3.3,4.4],dtype=str)
print(a1)
a2=np.array([1.1,2.2,3.3,4.4],dtype='str')
print(a2)

# typecasting from float to complex

a1 = np.array([3,4,5.45,6.12,6,7],dtype = complex)
a1

# typecasting from complex
# typecasting of complex is not possible to any data type

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1. 2. 3. 4.]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]
['1' '2' '3' '4']
['1' '2' '3' '4']


### Performing numeric opernation on np.array

In [13]:
# unlike list as np array is homogeneous datatype it is possible to directly apply
# operation on individual emlement directly 

a1 = np.array([3,4,5,6,7])
print(a1*10)  

a1 = np.array([3,4,5,6,7])
print(a1+10)

a1 = np.array([3,4,5,6,7])
print(a1-10)

a1 = np.array([30,40,50,60,70])
print(a1%10)

a1 = np.array([30,40,50,60,70])
print(a1//10)

[30 40 50 60 70]
[13 14 15 16 17]
[-7 -6 -5 -4 -3]
[0 0 0 0 0]
[3 4 5 6 7]


In [17]:
# converting np array to list

list1 = [3,4,5,6,7]
cubes = np.array(list1) ** 3
print(type(cubes)) # here type is 'numpy.ndarray'
list(cubes)

list1 = [3,4,5,6,7]
cubes = np.array(list1) ** 3
cubes.tolist()
print(cubes) 

list1 = [3,4,5,6,7]
cubes = (np.array(list1)**3).tolist()
print(cubes)

<class 'numpy.ndarray'>
[ 27  64 125 216 343]
[27, 64, 125, 216, 343]


### Dimensions in np array

In [30]:
# zero dim array
a1=np.array(10)
print(type(a1))
print(a1.ndim)
print(a1)
print(a1.shape)

# one dim array
a1=np.array([1,2,3,4,5,6])
print(type(a1))
print(a1.ndim)
print(a1)
print(a1.shape)

# two dim arrray
a1=np.array([[1,2,3],[2,3,4]])
print(type(a1))
print(a1.ndim)
print(a1)
print(a1.shape)

# three dim array
a1 = np.array([[[4,5,6],[7,102,40],[10,50,90],[1,2,3]],[[4,5,6],[7,102,40],[10,50,90],[1,2,3]]])
print(type(a1))
print(a1.ndim)
print(a1)
print(a1.shape)


<class 'numpy.ndarray'>
0
10
()
<class 'numpy.ndarray'>
1
[1 2 3 4 5 6]
(6,)
<class 'numpy.ndarray'>
2
[[1 2 3]
 [2 3 4]]
(2, 3)
<class 'numpy.ndarray'>
3
[[[  4   5   6]
  [  7 102  40]
  [ 10  50  90]
  [  1   2   3]]

 [[  4   5   6]
  [  7 102  40]
  [ 10  50  90]
  [  1   2   3]]]
(2, 4, 3)


### Indexing and Sclicing in np array

In [8]:
# 2d array
# [n][m]-->n is row and m is column
a2 = np.array([[2,3,4,8],[1,6,7,8]])
print('this is a2\n',a2)
print('*'*30)
print(a2[0][1])
print(a2[0,1])
print(a2[:,:2])
print('*'*30)

a3 = np.array([[2,3,4,8],[1,6,7,8],[10,20,30,54]])
print('this is a3\n',a3)
print('*'*30)
print(a3[1:,2:])
print(a3[:2,:2])
print('*'*30)

# 3d array
a1 = np.array([[[4,5,6],[7,102,40],[10,50,90],[1,2,3]],[[4,5,6],[7,102,40],[10,50,90],[1,2,3]]])
print('this is a1\n',a1)
print('*'*30)
print(a1[0,2:,1:])
print(a1[:,:,:2])
print('*'*30)


this is a2
 [[2 3 4 8]
 [1 6 7 8]]
******************************
3
3
[[2 3]
 [1 6]]
******************************
this is a3
 [[ 2  3  4  8]
 [ 1  6  7  8]
 [10 20 30 54]]
******************************
[[ 7  8]
 [30 54]]
[[2 3]
 [1 6]]
******************************
this is a1
 [[[  4   5   6]
  [  7 102  40]
  [ 10  50  90]
  [  1   2   3]]

 [[  4   5   6]
  [  7 102  40]
  [ 10  50  90]
  [  1   2   3]]]
******************************
[[50 90]
 [ 2  3]]
[[[  4   5]
  [  7 102]
  [ 10  50]
  [  1   2]]

 [[  4   5]
  [  7 102]
  [ 10  50]
  [  1   2]]]
******************************


### reshape()

In [50]:
# we can reshape only when multiplication is same as number of emlements
a1 = np.array([2,3,4,5,1,6,7,8,9,20,30,40])
print(a1.shape)
print('*'*30)
a1=a1.reshape(4,3)
print(a1)
print(a1.shape)
print('*'*30)

a1=a1.reshape(3,4)
print(a1)
print(a1.shape)
print('*'*30)

a1=a1.reshape(3,2,2)
print(a1)
print(a1.shape)
print('*'*30)



(12,)
******************************
[[ 2  3  4]
 [ 5  1  6]
 [ 7  8  9]
 [20 30 40]]
(4, 3)
******************************
[[ 2  3  4  5]
 [ 1  6  7  8]
 [ 9 20 30 40]]
(3, 4)
******************************
[[[ 2  3]
  [ 4  5]]

 [[ 1  6]
  [ 7  8]]

 [[ 9 20]
  [30 40]]]
(3, 2, 2)
******************************


### nditer()

In [54]:
# it is used to iterate numpy array

arr2 = np.array([[20, 30, 40], [ 5, 6, 1]])
for i in np.nditer(arr2):
    print(i)
    
a1=np.array([[[ 2,3],[ 4,5]],[[ 1 , 6],[ 7,  8]],[[ 9, 20],[30 ,40]]])
for i in np.nditer(a1):
    print(i)

20
30
40
5
6
1
2
3
4
5
1
6
7
8
9
20
30
40


### ndenumerate()

In [55]:
# can be used to get index ao each value in matrix
array1 = np.array([3,4,5,6,7,8])
for i,v in np.ndenumerate(array1):
    print(i,v)
print('*'*30)
a1=np.array([[[ 2,3],[ 4,5]],[[ 1 , 6],[ 7,  8]],[[ 9, 20],[30 ,40]]])
for i,v in np.ndenumerate(a1):
    print(i,v)


(0,) 3
(1,) 4
(2,) 5
(3,) 6
(4,) 7
(5,) 8
******************************
(0, 0, 0) 2
(0, 0, 1) 3
(0, 1, 0) 4
(0, 1, 1) 5
(1, 0, 0) 1
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8
(2, 0, 0) 9
(2, 0, 1) 20
(2, 1, 0) 30
(2, 1, 1) 40


### flaten

In [ ]:
Used to convert n-Dimensional array to 1-D array

In [12]:
a1 = np.array([[[3,4,5],[6,7,8]],[[10,20,30],[100,200,400]]])
a2 = a1.flatten()
print(a2)

[  3   4   5   6   7   8  10  20  30 100 200 400]


### ravel

In [ ]:
Used to covert n-D array to 1-D array
It returns only reference of original array
If we make changes in original array it will refelect in ravel 

In [14]:
array3 = np.array([[[3,4,5],[6,7,8]],[[10,20,30],[100,200,400]]])
print(array3)

array5 = array3.ravel()
print(array5)

array3[0,0,0]=1000

print(array3)
print(array5)

[[[  3   4   5]
  [  6   7   8]]

 [[ 10  20  30]
  [100 200 400]]]
[  3   4   5   6   7   8  10  20  30 100 200 400]
[[[1000    4    5]
  [   6    7    8]]

 [[  10   20   30]
  [ 100  200  400]]]
[1000    4    5    6    7    8   10   20   30  100  200  400]


### copy

In [ ]:
numpy copy always returns deep copy
changes in original array is not refelected in copy

In [15]:
arr1 = np.array([[4,5,6],[10,20,40]])
arr2 = arr1.copy()  # Deep Copy

arr2[1][0] = 1000

print("arr1 :\n",arr1)
print("arr2 :\n",arr2)

arr1 :
 [[ 4  5  6]
 [10 20 40]]
arr2 :
 [[   4    5    6]
 [1000   20   40]]


### Diff between copy and ravel


In [22]:
# copy
# creates deep copy of array
print('result of copy')
a1 = np.array([[4,5,6],[10,20,40]])
a2 = a1.copy()  # Deep Copy

a2[1][0] = 1000

print("a1 :\n",arr1)
print("*"*40)
print("a2 :\n",arr2)

print()
print("-"*40)
print()
print('result of ravel')

# ravel
# ravel returns 1d array as result
arr1 = np.array([[4,5,6],[10,20,40]])
arr2 = arr1.ravel()
print("arr2",arr2)

arr2[2] = 6666

print("arr1 :\n",arr1)
print("*"*40)
print("arr2 :\n",arr2)

result of copy
a1 :
 [[   4    5 6666]
 [  10   20   40]]
****************************************
a2 :
 [   4    5 6666   10   20   40]

----------------------------------------

result of ravel
arr2 [ 4  5  6 10 20 40]
arr1 :
 [[   4    5 6666]
 [  10   20   40]]
****************************************
arr2 :
 [   4    5 6666   10   20   40]


### Creating numpy arrays using zeros , ones and full function

In [33]:
# zeros
# syntax --> np.zeros((shape),dtype)
a1=np.zeros(10,dtype='i')
print(a1)
a2=np.zeros((5,4),'i')
print(a2)
a3=np.zeros((5,4),'f')
print(a3)

# ones
# syntax --> np.ones((shape),dtype)
o1=np.ones(10,dtype='i')
print(o1)
o2=np.ones((2,3),dtype='f')
print(o2)

# full
# syntax --> np.full((shape),value)
f1=np.full(10,4)
print(f1)
f2=np.full((4,5),6)
print(f2)

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1 1 1 1 1 1 1 1 1 1]
[[1. 1. 1.]
 [1. 1. 1.]]
[4 4 4 4 4 4 4 4 4 4]
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


### arange

In [35]:
# creates array from values within given range
# syntax --> np.arange(start,end,step)
a1=np.arange(1,10,1)
print(a1)
a2=np.arange(10,0,-2)
print(a2)

[1 2 3 4 5 6 7 8 9]
[10  8  6  4  2]


### around

In [38]:
# rounda values in array upto given number

# 1d array
a1=np.array([1.2222,3.4444,5.66666])
print(np.around(a1,2))

# 2d array
arr1 = np.array( [[4.5678,6.345678], [10.123456,9.3456]]) 
print(np.around(arr1,3))

# to round values in nested list
# first convert list to array and use around function and again convert to list using tolist function
l1=[[4.5678,6.345678], [10.123456,9.3456]]
a=np.array(l1)
r=np.round(a,2)
l2=r.tolist()
print(l2)

[1.22 3.44 5.67]
[[ 4.568  6.346]
 [10.123  9.346]]
[[4.57, 6.35], [10.12, 9.35]]


### linspace

In [ ]:
np.linspace(start, end, num = 50)
default it returns 50 values
It returns array of evenly spaced values between start to end

In [3]:
array1= np.linspace(10,19,10)
print(array1)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]


### eye

In [42]:
# Return a 2-D array with ones on the diagonal and zeros elsewhere.
# syntax --> np.eye(row,column,dtype)

a1=np.eye(4,dtype='i')
print(a1)

a2=np.eye(4,5,dtype='i')
print(a2)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


### identity

In [44]:
# syntax --> np.identiti(row,dtype)
arr1 = np.identity(4,dtype = int)
arr1

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

## random

In [ ]:
Used to generate random numbers
random:
    1. random.rand
    2. random.randint
    3. random.randn
    4. random.ranf

### random.rand

In [47]:
# It return random values between 0 to 1
# syntax --> np.random.rand(row,column)
array1 = np.random.rand(5)
print(array1)

a1=np.random.rand(2,3)
print(a1)


[0.71743219 0.13780183 0.24891006 0.44754076 0.36300001]
[[0.44243126 0.34481347 0.31794772]
 [0.31037688 0.75737875 0.53179365]]


### random.randint

In [49]:
# it returns random value between two values 
# syntax --> np.random.randint(start,end,size=(row,column))
a1=np.random.randint(10,20,10)
print(a1)

a2=np.random.randint(10,20,size=(4,5))
print(a2)

[11 15 17 17 15 12 12 17 11 13]
[[17 19 13 10 16]
 [16 13 11 16 13]
 [17 19 15 18 16]
 [12 13 11 11 15]]


### random.randn

### random.ranf

In [53]:
# It Returns values in 0 to 1
# syntax --> np.random.ranf((shape)
a1=np.random.ranf((3,6))
print(a1)
a2=np.random.ranf(3)
print(a2)

[[0.95768145 0.42072301 0.71686936 0.10010405 0.93218751 0.82124689]
 [0.1261437  0.93646262 0.6868182  0.0147514  0.68325002 0.52816037]
 [0.67940134 0.0099937  0.68611473 0.94894895 0.74901168 0.42852443]]
[0.89490184 0.06982163 0.18014113]


### append

In [ ]:
new_array = np.append(array1,array2,axis = None)
value >> n-D array
return 1d array if we do not mention axix
default axis is none so it will flatten given arrays and then append and return 1D array
axis = 0 >> Row operation
axis = 1 >> Columns operation

In [15]:
# appending single value to array
array1 = np.array([36, 35, 30, 18, 31, 21, 27, 24, 27, 17])
new_array = np.append(array1, 555)
print(new_array)

# appending 2 arrays to create new array
array2 = np.array([36, 35, 30, 18, 27, 17])
array3 = np.array([10,20,30,40])
new_array = np.append(array2, array3)
print(new_array)

array2 = np.array([36, 35, 30, 18, 27, 17])
array3 = np.array([[10,20],[30,40]])
new_array = np.append(array2, array3)
print(new_array)

array2 = np.array([[1,2],[3,4]])
array3 = np.array([[10,20],[30,40],[30,40]])
new_array = np.append(array2, array3)
print(new_array)

# when axis = 0 it will perform operation on row 
# elements are added in row i.e rows are created
# here in both array no of column should be same but rows can be different
array1 = np.array([[36, 35], [30, 18]])
array2 = np.array([[10,20],[30,40],[30,40]])
new_array = np.append(array1,array2,axis = 0) 
print("New Array \n",new_array)
print(new_array.shape)

# when axis = 1 it will perform operation on column
# elements are added in new clumns i.e column are created
# here no of rows in both array should be same but no of column can be different
array1 = np.array([[36, 35], [30, 18]])
array2 = np.array([[10,20,8],[30,40,8]])
new_array = np.append(array1,array2,axis = 1)
print("New Array \n",new_array)
print(new_array.shape)

[ 36  35  30  18  31  21  27  24  27  17 555]
[36 35 30 18 27 17 10 20 30 40]
[36 35 30 18 27 17 10 20 30 40]
[ 1  2  3  4 10 20 30 40 30 40]
New Array 
 [[36 35]
 [30 18]
 [10 20]
 [30 40]
 [30 40]]
(5, 2)
New Array 
 [[36 35 10 20  8]
 [30 18 30 40  8]]
(2, 5)


### concatenate

In [ ]:
np.concatenate([array1, array2, ...,arrayN],axis = 0)
dim of each array should be same
axis = 0 >> Rows
axis = 1 >> COlumns
default axis is 0 if we do not pass axis it takes 0 

In [23]:
# when axis = 1 it will perform operation on column
# elements are added in new clumns i.e column are created
# here no of rows in both array should be same but no of column can be different
array1 = np.array([[36, 35], [30, 18]])
array2 = np.array([[10,20,9],[30,40,9]])
array3 = np.array([[10,20],[30,40]])
new_array = np.concatenate([array1,array2,array3],axis = 1)
print("New Array \n",new_array)
print(new_array.shape)

# when axis = 0 it will perform operation on row 
# elements are added in row i.e rows are created
# here in both array no of co;umn should be same but rows can be different
array1 = np.array([[36, 35], [30, 18]])
array2 = np.array([[10,20],[30,40],[30,40]])
array3 = np.array([[10,20]])
new_array = np.concatenate([array1,array2,array3],axis=0)
print('\n',new_array)

New Array 
 [[36 35 10 20  9 10 20]
 [30 18 30 40  9 30 40]]
(2, 7)

 [[36 35]
 [30 18]
 [10 20]
 [30 40]
 [30 40]
 [10 20]]


### sort

In [ ]:
sorted_array = np.sort(array)
syntax --> np.sort(array,axis)
axis = 0 it will sort each column 
axis = 1 it will sort each row

np.sort(array1) --> sort in ascending oredr
-np.sort(-array1) --> sort in descending order

In [27]:
array1 = np.random.randint(20,50,size = 6)
print(array1)
sorted_array=np.sort(array1)
print(sorted_array)


array1 = np.random.randint(20,50,size = (3,4))
print(array1)
sorted_array=np.sort(array1,axis=0)
print(sorted_array)
sorted_array=np.sort(array1,axis=1)
print(sorted_array)

# sorting in ascending order
array1=np.array([1,20,13,6,4,8,20])
print(np.sort(array1))

# sorting in descending order
array1=np.array([1,20,13,6,4,8,20])
print(-np.sort(-array1))

[28 21 38 42 38 39]
[21 28 38 38 39 42]
[[35 40 20 33]
 [25 47 25 26]
 [35 37 46 36]]
[[25 37 20 26]
 [35 40 25 33]
 [35 47 46 36]]
[[20 33 35 40]
 [25 25 26 47]
 [35 36 37 46]]


### add

In [ ]:
matrix addn
requires same no of elements both arrays

In [30]:
m1 = np.random.randint(10,20,size = (2,2))
m2 = np.random.randint(20,40,size = (2,2))
print("matrix1 :\n",m1)
print("matrix2 :\n",m2)

addn= np.add(m1,m2)
print('addn is \n',addn)


m1=np.array([1,2,3])
m2=np.array([1,2])
print(np.add(m1,m2)) #not possible as no of elements id deffn


matrix1 = np.random.randint(10,20,size = (2,2))
matrix2 = np.random.randint(20,40,size = (3,2))
print("matrix1 :\n",matrix1)
print("matrix2 :\n",matrix2)
np.add(matrix1, matrix2) # cannot perform as size is diff (2,2) and (3,2)

matrix1 :
 [[12 14]
 [11 13]]
matrix2 :
 [[31 38]
 [30 22]]
addn is 
 [[43 52]
 [41 35]]


### multplication

In [31]:
matrix1 = np.random.randint(1,10,size = (2,2))
matrix2 = np.random.randint(10,20,size = (2,2))

print("matrix1 :\n",matrix1)
print("matrix2 :\n",matrix2)
np.multiply(matrix1, matrix2)

matrix1 :
 [[7 7]
 [6 8]]
matrix2 :
 [[14 19]
 [14 12]]


array([[ 98, 133],
       [ 84,  96]])

### dot product

In [ ]:
imp condition is no of columns in matrix1 = no of rows in matrix2 
result:
    no of rows= no of rows in matrix1
    no of column = no of column in matrix2

In [9]:
matrix1 = np.random.randint(1,10,size = (3,5))
matrix2 = np.random.randint(10,20,size = (5,4))
print("matrix1 :\n",matrix1)
print("matrix2 :\n",matrix2)
dot = np.dot(matrix1,matrix2)
x=np.matmul(matrix1,matrix2)#matmul can also be used to perform matrix multiplaction
print(dot)
print(x)

matrix1 :
 [[5 5 8 7 4]
 [4 3 1 7 9]
 [2 8 7 5 5]]
matrix2 :
 [[10 17 14 14]
 [14 12 11 11]
 [19 12 11 12]
 [16 16 18 15]
 [10 19 15 16]]
[[424 429 399 390]
 [303 399 361 350]
 [395 389 358 355]]
[[424 429 399 390]
 [303 399 361 350]
 [395 389 358 355]]


### math operation on array

In [41]:
array1 = np.array([200,500,700,300,800])

print(array1*10)
print(array1/10)
print(array1//10)
print(array1-10)
print(array1%10)
print(array1**2)
print(array1**3)

[2000 5000 7000 3000 8000]
[20. 50. 70. 30. 80.]
[20 50 70 30 80]
[190 490 690 290 790]
[0 0 0 0 0]
[ 40000 250000 490000  90000 640000]
[  8000000 125000000 343000000  27000000 512000000]


### floor

In [43]:
# here we perform floor dividion on each element
print(np.floor([4.23, 9.12, 1.3456, 10.67, 5.78]))
print(np.floor([[4.23, 9.12], [1.3456, 10.67]]))

[ 4.  9.  1. 10.  5.]
[[ 4.  9.]
 [ 1. 10.]]


### celi

In [45]:
# 4.23-->5 or 4.0000001-->5 and 4.0000-->4
array1 = np.array([4.23, 9.12, 1.3456, 10.67, 5.78])
print(np.ceil(array1))

array1 = np.array([[4.23, 9.00001], [1.3456, 10.67]])
print(np.ceil(array1))

[ 5. 10.  2. 11.  6.]
[[ 5. 10.]
 [ 2. 11.]]


### sqrt

In [47]:
a1=np.array([1,4,9,16,25])
print(np.sqrt(a1))

a2=np.array([200,300,400])
print(np.sqrt(a2))


[1. 2. 3. 4. 5.]
[14.14213562 17.32050808 20.        ]


### cbrt

In [48]:
a1=np.array([200,300,1000])
print(np.cbrt(a1))

[ 5.84803548  6.6943295  10.        ]


### where

In [56]:
# returns list of index where element is present
a1=np.array([1,2,2,4,5,6,2,2])
print(np.where(a1==2))

matrix1 = np.random.randint(1,10,size = (3,5))
print(matrix1)
print(np.where(matrix1==5))

(array([1, 2, 6, 7], dtype=int64),)
[[7 7 2 4 4]
 [6 1 1 8 5]
 [7 5 2 9 5]]
(array([1, 2, 2], dtype=int64), array([4, 1, 4], dtype=int64))


In [2]:
l1=[1,2,3]
l2=l1
l1=l2+[4,5,6]
print(l2)
l2=l1
print(l2)

[1, 2, 3]
[1, 2, 3, 4, 5, 6]


## numpy stats functions

In [ ]:
1. Mean
2. Median
3. Mode
4. Variance
5. Standard Devaitation

In [ ]:
1. np.mean()
# used to find mean value from array
# syntax --> np.mean(array1)

2. np.median()
# used to find median value from array
# syntax --> np.median(array1)

3. np.std()
# used to find value of standard deviation
# syntax --> np.std(array1)

4. np.var()
# used to find varaiance 
# syntax --> np.var(array1)

5. np.sum()
# used to find sum of values from array
# syntax --> np.sum(array1)

6. np.max()
# used to find max value from array
# syntax --> np.max(array1)

7. np.min()
# used to find min value from array
# syntax --> np.min(array1)

8. scipy.stats.mode()
# used to find moad value from array
# mode is not present in numpy lib so we need to import mode from scipy lib
# from scipy.stats import mode
# syntax --> mode(array1)

### mean

In [7]:
a1=np.random.randint(10,20,10)
print(a1)
mean= np.mean(a1)
print(mean)

a2=np.random.randint(10,20,(3,3))
print(a2)
print(np.mean(a2))



[16 13 10 19 11 14 11 14 18 18]
14.4
[[17 19 15]
 [11 12 10]
 [10 13 12]]
13.222222222222221


### median

In [11]:
a1=np.random.randint(10,20,10)
print(a1)
print(np.median(a1))

a1=np.random.randint(10,20,9)
print(a1)
print(np.median(a1))

a1=np.random.randint(10,20,(2,2))
print(a1)
print(np.median(a1))

[14 19 17 13 10 16 15 18 13 19]
15.5
[15 17 17 11 16 11 11 15 19]
15.0
[[11 16]
 [18 13]]
14.5


### std

In [13]:
a1=np.random.randint(10,20,5)
print(a1)
std=np.std(a1)
print(std)

a1=np.random.randint(10,20,(3,3))
print(a1)
std=np.std(a1)
print(std)

[15 14 15 15 13]
0.8
[[14 13 15]
 [18 10 13]
 [16 15 12]]
2.211083193570267


### variance

In [14]:
a1=np.random.randint(10,20,10)
print(a1)
print('variance',np.var(a1))

[18 16 18 11 17 19 14 14 18 17]
variance 5.5600000000000005


### mean median std deviation and variance

In [15]:
a1=np.random.randint(10,20,10)
print(a1)
print('mean is :',np.mean(a1))
print('median is :',np.median(a1))
print('standard deviation is :',np.std(a1))
print('variance is :',np.var(a1))

[17 10 10 19 11 10 17 10 11 14]
mean is : 12.9
median is : 11.0
standard deviation is : 3.3600595232822887
variance is : 11.290000000000001


## mode

In [ ]:
mode is not present in numpy lib
we need to import scipy lib and from that stat and mode
from scipy.stats import mode

In [5]:
from scipy.stats import mode

In [6]:
array2 = np.array([17, 27, 27,29,27])
Mode = mode(array2)
print(Mode)
print("Mode is :",Mode)
Mode[0][0]

ModeResult(mode=array([27]), count=array([3]))
Mode is : ModeResult(mode=array([27]), count=array([3]))


C:\Users\abhi\AppData\Local\Temp\ipykernel_1912\4237380603.py:2: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  Mode = mode(array2)


27

### max min sum

In [22]:
a1=np.random.randint(10,20,10)
print(max(a1))
print(min(a1))
print(sum(a1))

19
11
158


## numpy linear algebra functions

In [ ]:
1. np.linalg.solve()
# it is used to solve quadratic equations
# syntax --> np.linalg.solve(array1,array2)

2. np.linalg.inv()
# it is used to get inverse of array
# syntax --> np.linalg.inv()

3. np.polynomial.Polynomial()
# it is used to create polynomial equation
# syntax --> np.polynomial.Polynomial

4.poly.roots()
# it is used to find roots of given polynomial function
# syntax --> equation1.roots()

5. np.linalg.eig()
# it is used to get eigen vectors of matrix
# syntax --> np.linalg.eig(array1)

6. np.linalg.eigvals()
# it is used to get eigen values
# syntax --> np.linalg.eigenvalues(array1)

In [27]:
# how to solve quadratic equations
# 1x+2y=1 4x+5y=2

a1=np.array([[1,2],[4,5]])
a2=np.array([1,2])
result = np.linalg.solve(a1,a2)
print(result)

a1=np.array([])

# 2x + 3y + 5z = 100 3x + 9y + 4z = 140 5x + 3y + 7z = 120
a1 = np.array([[2,3,5],[3,9,4],[5,3,7]])
a2 = np.array([100,140,120])
print("Array A is :\n",a1)
print("Array B is :\n",a2)
result=np.linalg.solve(a1,a2)
print(result)

[-0.33333333  0.66666667]
Array A is :
 [[2 3 5]
 [3 9 4]
 [5 3 7]]
Array B is :
 [100 140 120]
[-3.7037037   9.87654321 15.55555556]


### inverse of array

In [29]:
a1 = np.array([[2,3],[3,9]])
np.linalg.inv(a1)

array([[ 1.        , -0.33333333],
       [-0.33333333,  0.22222222]])

### roots

In [32]:
# to create polynomial equation
a1=np.polynomial.Polynomial([1,2,3])
print(a1)

# to find roots of polynomial equation
a1=np.polynomial.Polynomial([1,2,3])
print(a1.roots())

a2=np.polynomial.Polynomial([4,5,2])
print(a2.roots())

1.0 + 2.0 x**1 + 3.0 x**2
[-0.33333333-0.47140452j -0.33333333+0.47140452j]
[-1.25-0.66143783j -1.25+0.66143783j]


In [34]:
from numpy.polynomial import Polynomial

poly = Polynomial([3,4,2,1])
poly

Polynomial([3., 4., 2., 1.], domain=[-1,  1], window=[-1,  1])

### eigen values and eigen vectors

In [33]:
array1=np.random.randint(10,20,(3,3))
eigen_values, eigen_vectors = np.linalg.eig(array1)
print(eigen_values)
print(eigen_vectors)

[40.78659907 -5.20749179 -0.57910728]
[[ 0.63774354  0.84292101 -0.0067697 ]
 [ 0.52451425 -0.47799727 -0.74334823]
 [ 0.56406381 -0.24698741  0.66887038]]


## numpy lograthmic functions

In [ ]:
1. np.log()
# it gives values of natura log
# syntax --> np.log(array1)

2. np.log2()
# it gives values of log to base 2
# syntax --> np.log2(array1)

3. np.log10()
# it gives values of log to base 10
# syntax --> np.log10(array1)

In [43]:
# np.log() --> natural log values
print(np.log(10))

# lograthmic tyransformation

a1=np.array([10,20,30,40])
print(np.log(a1))

# np.log2() --> log to the base 2
a1=np.array([1,2,3,4])
print(np.log2(a1))

# np.log10() --> log to the base 10
a1=np.array([10,20,30,45])
print(np.log10(a1))

2.302585092994046
[2.30258509 2.99573227 3.40119738 3.68887945]
[0.        1.        1.5849625 2.       ]
[1.         1.30103    1.47712125 1.65321251]


## numpy trigrometric functions

In [ ]:
1. np.sin()
# used to get sin values

2. np.cos()
# used to get cos values

3. np.tan()
# used to get tan values

4. np.deg2rad()
# used to convert degree to radians

5. np.rad2deg()
# used to conver radians to degree

In [54]:
# np.pi-->180 degree

# np.sin()
print(np.sin(np.pi/2)) # sin(90)
print(np.sin(np.pi/3)) # sin(60)
print(np.sin(np.pi/4)) # sin(45)
print(np.sin(np.pi/6)) # sin(30)

# np.cos()
print(np.sin(np.pi/2)) # cos(90)
print(np.sin(np.pi/3)) # cos(60)
print(np.sin(np.pi/4)) # cos(45)
print(np.sin(np.pi/6)) # cos(30)

# np.tan()
print(np.sin(np.pi/2)) # tan(90)
print(np.sin(np.pi/3)) # tan(60)
print(np.sin(np.pi/4)) # tan(45)
print(np.sin(np.pi/6)) # tan(30)

# degreetorandians
print(np.deg2rad(30))
print(np.deg2rad(45))
print(np.deg2rad(60))
print(np.deg2rad(90))

degree=np.array([30,45,60,90])
radians=np.deg2rad(degree)
print('values in radians :',radians)

1.0
0.8660254037844386
0.7071067811865476
0.49999999999999994
1.0
0.8660254037844386
0.7071067811865476
0.49999999999999994
1.0
0.8660254037844386
0.7071067811865476
0.49999999999999994
0.5235987755982988
0.7853981633974483
1.0471975511965976
1.5707963267948966
values in radians : [0.52359878 0.78539816 1.04719755 1.57079633]


## Important numpy interview questions

### How to perform matrix multiplication or dot product

In [ ]:
1--> np.matmul(array1,array2)
2--> np.dot(array1,array2)

### NumPy program with string functions

In [14]:
x=np.array(['a','B','cA'])
# to convert all array element to upper case
print(np.char.upper(x))
# to convert all array element to lower case
print(np.char.lower(x))
# to convert all array element to titel case
print(np.char.title(x))
# to convert all array element to swapcase case
print(np.char.swapcase(x))

['A' 'B' 'CA']
['a' 'b' 'ca']
['A' 'B' 'Ca']
['A' 'b' 'Ca']


### Filter Row of A Numpy Array 

In [35]:
# to filter rows based on perticular condition
x=np.array([[1,2,-3],[2,3,4],[4,-5,6]])
print(x)

# if we wand to find only index of rows having given condition
r=np.where(x<0)[0]
print('rows index following given condition is:',r)

# if we want to display all rows from array following condition 
print('rows following given condition \n',x[np.any(x<0,axis=1)])


[[ 1  2 -3]
 [ 2  3  4]
 [ 4 -5  6]]
rows index following given condition is: [0 2]
rows following given condition 
 [[ 1  2 -3]
 [ 4 -5  6]]


### Remove rows with Null values

In [41]:
x=np.array([[1,2,np.nan],[2,3,4],[np.nan,-5,6]])
print(x)
# to print all rows from array having at least one null vaule
print(x[np.isnan(x).any(axis=1)])

[[ 1.  2. nan]
 [ 2.  3.  4.]
 [nan -5.  6.]]
[[ 1.  2. nan]
 [nan -5.  6.]]


### Multiply String Elements in

In [44]:
x=np.array(['a','b','c'])
print(x)
r=np.char.multiply(x,4)
print(r)

['a' 'b' 'c']
['aaaa' 'bbbb' 'cccc']


### Find the minimum value with Numpy along axis 

In [47]:
x=np.array([[1,2,3],[5,6,7],[10,3,4]])
print(x)
r=np.apply_along_axis(lambda x : np.min(x),arr=x,axis=1)
r

[[ 1  2  3]
 [ 5  6  7]
 [10  3  4]]


array([1, 5, 3])

### Fill diagonal value in Numpy Array -

### Checking and filling number in Numpy Array

### Padding in Numpy Array

In [52]:
x=np.array([[1,2,3],[2,3,4],[5,5,6]])
# np.pad(array,pad_width,mode,constant_value)
np.pad(x,pad_width=2,mode='constant',constant_values=8)


array([[8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8],
       [8, 8, 1, 2, 3, 8, 8],
       [8, 8, 2, 3, 4, 8, 8],
       [8, 8, 5, 5, 6, 8, 8],
       [8, 8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8, 8]])

### Numpy Squeeze function in Python 

### Compare two Numpy Arrays

### Determine Memory size of Numpy array